name: CI â€¢ Linux (ARM64)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install Crystal
        run: |
          curl -fsSL https://packagecloud.io/84codes/crystal/gpgkey | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/84codes_crystal.gpg > /dev/null
          . /etc/os-release
          echo "deb https://packagecloud.io/84codes/crystal/$ID $VERSION_CODENAME main" | sudo tee /etc/apt/sources.list.d/84codes_crystal.list
          sudo apt-get update -y
          sudo apt-get install -y crystal

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libgtk-3-dev

      - name: Install dependencies
        run: shards install

      - name: Download libui library
        run: |
          crystal run download.cr
          ls libui

      - name: Run tests
        run: crystal spec

      - name: Build all examples
        run: |
          ls examples/*.cr | xargs -P 0 -I {} crystal build {}
          ls
